version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/scripts:/docker-entrypoint-initdb.d  # Монтируем скрипты

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=marketplace
      - DB_PASSWORD=password
      - DB_NAME=marketplace
      - JWT_SECRET=your-secret-key
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  postgres_data:
